name: toc_machine_trading_fe
description: "Status of trade agent, let user query analyzed stocks."
publish_to: "none"
version: 4.2.71+40134

environment:
  sdk: ^3.6.0

dependencies:
  another_flushbar: ^1.12.30
  carousel_slider: ^5.1.1
  cronet_http: ^1.4.0
  cupertino_http: ^2.2.0
  date_format: ^2.0.9
  email_validator: ^3.0.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  google_mobile_ads: ^6.0.0
  http: ^1.4.0
  in_app_purchase: ^3.2.3
  in_app_purchase_storekit: ^0.4.3
  intl: ^0.20.2
  k_chart: ^0.7.1
  path: ^1.9.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  protobuf: ^3.1.0
  pull_to_refresh: ^2.0.0
  scrollable_positioned_list: ^0.3.8
  sqflite: ^2.4.2
  syncfusion_flutter_charts: ^30.1.41
  syncfusion_flutter_treemap: ^30.1.41
  table_calendar: ^3.2.0
  toc_trade_protobuf: ^0.1.11
  url_launcher: ^6.3.2
  wakelock_plus: ^1.3.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/background.png
  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Black.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Bold.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-ExtraBold.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-ExtraLight.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Light.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Medium.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Regular.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-SemiBold.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Thin.ttf
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: assets/icon.png
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  background_image: assets/background.png
