name: toc_machine_trading_fe
description: "Status of trade agent, let user query analyzed stocks."
publish_to: "none"
version: 4.2.71+40133

environment:
  sdk: ^3.6.0

dependencies:
  another_flushbar: ^1.12.30
  carousel_slider: ^5.0.0
  cronet_http: ^1.3.2
  cupertino_http: ^2.0.1
  date_format: ^2.0.9
  email_validator: ^3.0.0
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_slidable: ^3.1.2
  flutter_spinkit: ^5.2.1
  google_mobile_ads: ^5.2.0
  http: ^1.2.2
  in_app_purchase: ^3.2.0
  in_app_purchase_storekit: ^0.3.20+2
  intl: ^0.19.0
  k_chart: ^0.7.1
  path: ^1.9.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  protobuf: ^3.1.0
  pull_to_refresh: ^2.0.0
  scrollable_positioned_list: ^0.3.8
  sqflite: ^2.4.1
  syncfusion_flutter_charts: ^28.1.35
  syncfusion_flutter_treemap: ^28.1.35
  table_calendar: ^3.1.3
  toc_trade_protobuf: ^0.1.11
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.8
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/background.png
  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Black.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Bold.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-ExtraBold.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-ExtraLight.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Light.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Medium.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Regular.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-SemiBold.ttf
        - asset: assets/fonts/noto_sans_moto/NotoSansMono-Thin.ttf
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: assets/icon.png
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  background_image: assets/background.png
