name: toc_machine_trading_fe
description: "Status of trade agent, let user query analyzed stocks."
publish_to: "none"
version: 4.2.0+40045

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  protobuf: ^3.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: assets/app_icon.png
  ios: true
  remove_alpha_ios: true
