default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON']
    )
  end
end
